name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        test_target: [unit-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install marp-cli
        run: brew install marp-cli

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run make ${{ matrix.test_target }}
